 /*
  * The contents of this file are subject to the Mozilla Public
  * License Version 1.1 (the "License"); you may not use this file
  * except in compliance with the License. You may obtain a copy of
  * the License at http://www.mozilla.org/MPL/
  *
  * Software distributed under the License is distributed on an "AS
  * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
  * implied. See the License for the specific language governing
  * rights and limitations under the License.
  *
  * The Original Code is the Bugzilla Testopia Java API.
  *
  * The Initial Developer of the Original Code is Andrew Nelson.
  * Portions created by Andrew Nelson are Copyright (C) 2006
  * Novell. All Rights Reserved.
  *
  * Contributor(s): Andrew Nelson <anelson@novell.com>
  *					Jason Sabin <jsabin@novell.com>
  */
package testopia.API;

import java.util.HashMap;
import java.util.Map;

import org.apache.xmlrpc.XmlRpcException;

/**
 * 
 * @author anelson, bstice 
 * Creates a wrapper class for the TestRunCase
 */
public class TestCaseRun extends TestopiaObject{
	public enum Statuses {IDLE, PASSED, FAILED, RUNNING, PAUSED, BLOCKED, ERROR};


	private Integer caseRunID; 
			
	//stores the updated value until it's pushed to testopia with an update
	private StringAttribute notes = this.newStringAttribute("notes", null);
	private StringAttribute status= this.newStringAttribute("status", null);
	private IntegerAttribute assigneeID= this.newIntegerAttribute("assignee", null);

	private IntegerAttribute caseID= this.newIntegerAttribute("case_id", null);
	private IntegerAttribute runID= this.newIntegerAttribute("run_id", null);
	private IntegerAttribute buildID= this.newIntegerAttribute("build", null);
	private IntegerAttribute environmentID= this.newIntegerAttribute("environment", null);


	

	/**
	 * Use this constructor if you just want to use gets
	 * @param userName your bugzilla username
	 * @param password your bugzilla password
	 * @param caseRunID ID generated by bugzilla - can be null
	 * @param url URL - the url of the testopia server that you want to connect to
	 */
	public TestCaseRun(Session session, int caseRunID)
	{
		this.session   = session; 
		this.caseRunID = caseRunID; 
	}
	
	/**
	 * Use this constructor if you want to do sets and gets
	 * @param userName your bugzilla username
	 * @param password your bugzilla password 
	 * @param caseID ID used to get the case
	 * @param runID test run number
	 * @param buildID ID generated by bugzilla
	 * @param environmentID ID generated by bugzilla
	 * @param caseRunID ID generated by bugzilla - can be null
	 * @param url URL - the url of the testopia server that you want to connect to
	 */
	public TestCaseRun(Session session,	int runID,  int caseID, int buildID, int environmentID) 
	{
		this.session = session;
		this.caseID.set(caseID);
		this.runID.set(runID); 
		this.buildID.set(buildID); 
		this.environmentID.set(environmentID);
	}
	
	/**
	 * Updates are not called when the .set is used. You must call update after all your sets
	 * to push the changes over to testopia.
	 * @throws TestopiaException if planID is null 
	 * @throws XmlRpcException
	 * (you made the TestCase with a null caseID and have not created a new test plan)
	 */
	public Map<String,Object> update() throws TestopiaException, XmlRpcException
	{
		if (runID == null) 
			throw new TestopiaException("runID is null.");
		//update the testRunCase
		return super.update("TestCaseRun.update", caseRunID);
	}
	
	/**
	 * Calls the create method with the attributes as-is (as set via constructors
	 * or setters).  
	 * @return a map of the newly created object
	 * @throws XmlRpcException
	 */
	public Map<String,Object> create() throws XmlRpcException{
		return super.create("TestCaseRun.create");			
	}
	
	/**
	 * used to create a testRunCase
	 * @param assigneeID
	 * @param caseRunStatusID
	 * @param caseTextVersion
	 * @return caseRunID
	 * @throws XmlRpcException 
	 * @throws Exception
	 *//*
	public int makeTestCaseRun(int assigneeID, int caseTextVersion)
	throws TestopiaException, XmlRpcException 
	{
		if (canUpdate == false) 
			throw new TestopiaException(
					"You can't update if you use the 3 parameter constructor, "+
					"you must use the constuctor with 7 parameters");
		
	    //set the values for the test case
		Map<String, Object> map = getDirtyAttributesMap();
				
		return (Integer)callXmlrpcMethod("TestCaseRun.create", map);
		
	}*/
	
	/**
	 * Updates are not called when the .set is used. You must call update after all your sets
	 * to push the changes over to testopia.
	 * @throws Exception will throw an exception if you used the 3 param constuctor. 
	 */
	/*public void update()
	throws TestopiaException, XmlRpcException
	{
		if (canUpdate == false)
			throw new TestopiaException(
					"You can't update if you use the 3 parameter constructor, "+
					"you must use the constuctor with 7 parameters");
		
		//hashmap to store attributes to be updated
		Map<String, Object> map = getDirtyAttributesMap();
				
		if (map.size() > 0) {
			callXmlrpcMethod("TestCaseRun.update", runID, caseID, buildID, environmentID, map);
			this.cleanAllAttributes();
		}
	}*/
	
	/**
	 * 
	 * @return a hashMap of all the values found. Returns null if there is an error
	 * and the TestCaseRun cannot be returned
	 * @throws XmlRpcException 
	 */
	@SuppressWarnings("unchecked")
	public Map<String, Object> getAttributes()
	throws XmlRpcException
	{
		Map m = (Map<String, Object>)callXmlrpcMethod("TestCaseRun.get", caseRunID);
		syncAttributes(m);
		return m;
		
	}

	/**
	 * This is used to append a note
	 * @param notes string - the note you want entered into the testCaseRun
	 */
	public void setNotes(String notes)
	{	
		this.notes.set(notes);
	}
	
	/**
	 * This is used to change the testCaseRun status (2 for pass, 3 for fail)
	 * @param status int - the status you want to change the testCaseRun to
	 */
	public void setStatus(Statuses status)
	{
		this.status.set(status.toString());
	}
	

	
	
	/**
	 * Changes the assigneeID of the testCaseRun
	 * @param assigneeID
	 */
	public void setAssigneeID(int assigneeID)
	{
		this.assigneeID.set(assigneeID); 
	}
	
	/**
	 * @return the caseID
	 */
	public int getCaseID() {
		return caseID.get();
	}

	/**
	 * @return the runID
	 */
	public int getRunID() {
		return runID.get();
	}

	/**
	 * @return the buildID
	 */
	public int getBuildID() {
		return buildID.get();
	}

	/**
	 * @return the environmentID
	 */
	public int getEnvironmentID() {
		return environmentID.get();
	}

	/**
	 * @return the caseRunID
	 */
	public Integer getCaseRunID() {
		return caseRunID;
	}


	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes.get();
	}

	/**
	 * @return the caseStatus
	 */
	public Statuses getStatus() {
		return Statuses.valueOf(status.get());
	}

	/**
	 * @return the assigneeID
	 */
	public int getAssigneeID() {
		return assigneeID.get();
	}
	
	public void setCaseID(Integer caseID) {
		this.caseID.set(caseID);
	}

	public void setRunID(Integer runID) {
		this.runID.set(runID);
	}

	public void setBuildID(Integer buildID) {
		this.buildID.set(buildID);
	}

	public void setEnvironmentID(Integer environmentID) {
		this.environmentID.set(environmentID);
	}

}
